package mpp.view;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

public class LoginWindow implements ActionListener, KeyListener, DocumentListener {
    private JPanel mainPane;
    private JTextField tfUserName;
    private JPasswordField tfPassword;
    private JButton loginButton;

    private LibAppWindow libAppWindow;

    public LoginWindow(LibAppWindow libAppWindow) {
        tfUserName.getDocument().addDocumentListener(this);
        tfPassword.getDocument().addDocumentListener(this);
        loginButton.setEnabled(false);
        this.libAppWindow = libAppWindow;
        // add the listener to the textField
        loginButton.addKeyListener(this);
        tfPassword.addKeyListener(this);
        tfUserName.addKeyListener(this);
        loginButton.addActionListener(e ->
                libAppWindow.validateUser(tfUserName.getText().trim(), String.valueOf(tfPassword.getPassword()))
        );
    }

    public LibAppWindow getLibAppWindow() {
        return libAppWindow;
    }

    public void setLibAppWindow(LibAppWindow libAppWindow) {
        this.libAppWindow = libAppWindow;
    }

    public JPanel getMainPane() {
        return mainPane;
    }

    public void setMainPane(JPanel mainPane) {
        this.mainPane = mainPane;
    }

    @Override
    public void keyPressed(KeyEvent e) {
        if (e.getKeyCode() == KeyEvent.VK_ENTER) {
            libAppWindow.validateUser(tfUserName.getText().trim(), String.valueOf(tfPassword.getPassword()));
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {

    }

    @Override
    public void keyTyped(KeyEvent e) {

    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    @Override
    public void actionPerformed(ActionEvent e) {

    }

    private void updateLoginButton() {
        loginButton.setEnabled(false);
        if (tfPassword.getPassword().length > 0 && !tfUserName.getText().trim().isEmpty()) {
            loginButton.setEnabled(true);
        }
    }

    @Override
    public void insertUpdate(DocumentEvent e) {
        updateLoginButton();
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        updateLoginButton();
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        updateLoginButton();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        mainPane.add(panel1, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setAlignmentX(0.0f);
        label1.setAlignmentY(0.0f);
        label1.setAutoscrolls(false);
        label1.setMaximumSize(new Dimension(40, 16));
        label1.setText("LOGIN");
        panel1.add(label1);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        mainPane.add(panel2, BorderLayout.CENTER);
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer1, gbc);
        tfPassword = new JPasswordField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.weightx = 0.5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(tfPassword, gbc);
        tfUserName = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(tfUserName, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Username");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 10, 0, 0);
        panel2.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Password");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 10, 0, 0);
        panel2.add(label3, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.weightx = 0.01;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel2.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.weighty = 2.0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel2.add(spacer4, gbc);
        loginButton = new JButton();
        loginButton.setAlignmentY(0.0f);
        loginButton.setText("Login");
        loginButton.setVerticalAlignment(0);
        loginButton.setVerticalTextPosition(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(loginButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }
}


